version: '3'

services:

  # Database
  mysql:
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./deploy/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=openiot
      - MYSQL_USER=openiot
      - MYSQL_PASSWORD=openiot
      - MYSQL_ROOT_PASSWORD=123456

  # Redis
  redis:
    image: "redis:latest"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /usr/local/redis:/var/lib/redis
    environment:
      - REDIS_PASSWORD=openiot
      - ALLOW_EMPTY_PASSWORD=no

  # Message Broker
  rabbitmq:
    image: "rabbitmq:latest"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=openiot
      - RABBITMQ_DEFAULT_PASS=openiot

  # k-v store
  etcd:
    image: "quay.io/coreos/etcd:v3.5.5"
    restart: always
    ports:
      - 2379:2379
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_API=3

  # Tracer
  jaeger:
    image: "jaegertracing/all-in-one:latest"
    restart: always
    ports:
      - 16686:16686
      - "6381:6381"

  # Monitor
  prometheus:
    image: "prom/prometheus:latest"
    restart: always
    ports:
      - 9090:9090
    # volumes:
    #   - ./prometheus.yml:/etc/prometheus/prometheus.yml