AppMode = 'debug'
AppName = 'openiot-hub'

[Avatar]

[DB]
Name = 'openiot'
Password = '123456'
Port = 3306
Type = 'mysql'
User = 'openiot'

[RabbitMQ]
RabbitMQ = 'amqp'
RabbitMQHost = 'localhost'
RabbitMQPassWord = 'openiot'
RabbitMQPort = '5672'
RabbitMQUser = 'openiot'

[Redis]
DbName = 3
IdleTimeout = 200
MaxActive = 30
MaxIdle = 30
Password = 'openiot'
Port = 6379

[SMS]

[Server]
ReadTimeout = 60
WriteTimeout = 60

[Wechat]
AppID = ''
Secret = ''
