// Code generated by Kitex v0.7.3. DO NOT EDIT.
package deviceservice

import (
	device "github.com/OpenIoT-Hub/openiot-server/kitex_gen/device"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler device.DeviceService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
