// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userregisterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _devicecreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deviceremoveMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deviceupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdevicebyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listdeviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pingMw() []app.HandlerFunc {
	// your code...
	return nil
}
